###Data analyses for RGT Superset publication
  #Large-N rat data enables phenotyping of risky decision-making: A retrospective analysis of brain injury on the Rodent Gambling Task
  #Cole Vonder Haar1,2, Michelle A. Frankot1, A. Matthew Reck1, Virginia Milleson1 & Kris M. Martens1,2
  #Frontiers in Neuroscience

data<-read.csv("RGT-superset.csv", na.strings="")




##Rename relevant variables, and remove irrelevant variables 
colnames(data)[colnames(data)=="Choice.P1.4."] <- "ChoiceOption"
#colnames(data)[colnames(data)=="Session.1"] <- "Session_norm"
data$SbjID<-paste(data$Study_ID, data$Subject, sep="-")
data<-subset(data, Session_norm>0)
	#Make sure you have validated your data before doing this as it will remove any sessions where someone forgot to insert the session #




##Summary Data Calculations


##Process a Dataset for doing choice analyses
	#Choice is separate because there are 4 observations which would replicate all other variables 4x and artificially inflate power
			library(dplyr)
			library(tidyr)
	#Count function tabulates first option by whatever you list
	#Make sure to include whatever grouping variables are relevant to your dataset
			ChoiceSummary<-data %>% count(ChoiceOption, SbjID, Session_norm, Week, Injury, Diet, Drug, Pre.Injury, Study_ID) 
			colnames(ChoiceSummary)[colnames(ChoiceSummary)=="n"] <- "ChoiceCount"
	#Remove all zero values (prematures + omissions) from this set
			ChoiceSummary<-subset(ChoiceSummary, ChoiceOption!=0)
			
	#Zeros (e.g., 0 P4 choice) are not included in count() function, so we need to add them back in
	#Make a set of columns all equal to 0 for each option, then we will bring those into row format
	#Datasets with unique variables (HFD, CCI-D) need to be done separately

	#This will create a zero for all options, and we will add the existing data to it for CCI-A & CCI-E
			temp<-aggregate(ChoiceCount~SbjID+Session_norm+Week+Injury+Pre.Injury+Study_ID, mean, data=subset(ChoiceSummary, Study_ID!="HFD-A" & Study_ID!="CCI-D"))
				#to get a lit of unique sessions by subject. Outcome variable (ChoiceCount) is irrelevant
				#Must retain list of all variables to prevent NAs
			temp<-subset(temp, select=-ChoiceCount)		#delete irrelevant mean variable
			temp$P1<-0			#write in zero'd columns
			temp$P2<-0
			temp$P3<-0
			temp$P4<-0
			temp<-gather(temp, ChoiceOption, ChoiceZero, P1:P4, factor_key=T)
				#Will translate from columns to rows, giving a new variable "ChoiceZero" to be merged with other set
			levels(temp$ChoiceOption)<-c(1,2,3,4)
				#correct the P's that were needed for column names
			ChoiceSummary<-merge(ChoiceSummary,temp, by=c("ChoiceOption", "SbjID","Session_norm", "Week", "Injury", "Pre.Injury", "Study_ID"), all=T)
				#Merge the two datasets back
	#This will create a zero for all options, and we will add the existing data to it for HFD-A
			temp<-aggregate(ChoiceCount~SbjID+Session_norm+Week+Injury+Pre.Injury+Study_ID+Diet, mean, data=subset(ChoiceSummary, Study_ID=="HFD-A"))
			temp<-subset(temp, select=-ChoiceCount)		#delete irrelevant mean variable
			temp$P1<-0			#write in zero'd columns
			temp$P2<-0
			temp$P3<-0
			temp$P4<-0
			temp<-gather(temp, ChoiceOption, ChoiceZero, P1:P4, factor_key=T)
				#Will translate from columns to rows, giving a new variable "ChoiceZero" to be merged with other set
			levels(temp$ChoiceOption)<-c(1,2,3,4)
				#correct the P's that were needed for column names
			ChoiceSummary<-merge(ChoiceSummary,temp, by=c("ChoiceOption", "SbjID","Session_norm", "Week", "Injury", "Pre.Injury", "Study_ID", "Diet"), all=T)
				#Merge the two datasets back
	#This will create a zero for all options, and we will add the existing data to it for CCI-D
			temp<-aggregate(ChoiceCount~SbjID+Session_norm+Week+Injury+Pre.Injury+Study_ID+Drug, mean, data=subset(ChoiceSummary, Study_ID=="CCI-D"))
			temp<-subset(temp, select=-ChoiceCount)		#delete irrelevant mean variable
			temp$P1<-0			#write in zero'd columns
			temp$P2<-0
			temp$P3<-0
			temp$P4<-0
			temp<-gather(temp, ChoiceOption, ChoiceZero, P1:P4, factor_key=T)
				#Will translate from columns to rows, giving a new variable "ChoiceZero" to be merged with other set
			levels(temp$ChoiceOption)<-c(1,2,3,4)
				#correct the P's that were needed for column names
			ChoiceSummary<-merge(ChoiceSummary,temp, by=c("ChoiceOption", "SbjID","Session_norm", "Week", "Injury", "Pre.Injury", "Study_ID", "Drug"), all=T)
				#Merge the two datasets back
	#Adjust the dataframe we've created
		ChoiceSummary$ChoiceCount[is.na(ChoiceSummary$ChoiceCount)]<-0
			#Replace any NAs that were generated by new data with 0s
		ChoiceSummary<-ChoiceSummary[,-c(11:13)]
		
	#Calculate total choices & merge back in with dataset
			temp<-aggregate(ChoiceCount~Session_norm+SbjID+Week, sum, data=ChoiceSummary)
			colnames(temp)[colnames(temp)=="ChoiceCount"] <- "TotChoice"
			ChoiceSummary<-merge(ChoiceSummary, temp, by=c("Session_norm","SbjID","Week"), all=T)
	#Obtained reinforcers per option
		temp<-aggregate(Pellets~ChoiceOption+Session_norm+SbjID+Week, sum, data=data)
		temp<-subset(temp, ChoiceOption!=0)
		ChoiceSummary<-merge(ChoiceSummary, temp, by=c("SbjID", "Session_norm", "SbjID", "Week", "ChoiceOption"), all=T)
		ChoiceSummary$Pellets[is.na(ChoiceSummary$Pellets)]<-0
	#Punishment duration per option
		temp<-aggregate(Pun_Dur~ChoiceOption+Session_norm+SbjID+Week, sum, data=data)
		temp<-subset(temp, ChoiceOption!=0)
		ChoiceSummary<-merge(ChoiceSummary, temp, by=c("SbjID", "Session_norm", "SbjID", "Week", "ChoiceOption"), all=T)
		ChoiceSummary$Pun_Dur[is.na(ChoiceSummary$Pun_Dur)]<-0
	#Calculate WinStay data by choice option
		temp<-data %>% count(SbjID, Session_norm, Pre.Injury, Week, LastChoice, WinStay)
		temp<-subset(temp, !is.na(WinStay))
		temp<-temp %>% spread(WinStay, n)
		colnames(temp)[colnames(temp)=="1"]<-"WinStay"
		colnames(temp)[colnames(temp)=="0"]<-"WinShift"
		temp$WinStay[is.na(temp$WinStay)]<-0
		temp$WinShift[is.na(temp$WinShift)]<-0
		temp$TotWins<-temp$WinStay+temp$WinShift
		colnames(temp)[colnames(temp)=="LastChoice"]<-"ChoiceOption"
		ChoiceSummary<-merge(ChoiceSummary, temp, by=c("SbjID", "Session_norm", "Pre.Injury", "Week", "ChoiceOption"), all=T)
		ChoiceSummary$WinShift[is.na(ChoiceSummary$WinShift)]<-0; ChoiceSummary$WinStay[is.na(ChoiceSummary$WinStay)]<-0; ChoiceSummary$TotWins[is.na(ChoiceSummary$TotWins)]<-0
	#Calculate LoseShift data by choice option
		temp<-data %>% count(SbjID, Session_norm, Week, LastChoice, LoseShift)
		temp<-subset(temp, !is.na(LoseShift))
		temp<-temp %>% spread(LoseShift, n)
		colnames(temp)[colnames(temp)=="1"]<-"LoseShift"
		colnames(temp)[colnames(temp)=="0"]<-"LoseStay"
		temp$LoseShift[is.na(temp$LoseShift)]<-0
		temp$LoseStay[is.na(temp$LoseStay)]<-0
		temp$TotLosses<-temp$LoseShift+temp$LoseStay
		colnames(temp)[colnames(temp)=="LastChoice"]<-"ChoiceOption"
		ChoiceSummary<-merge(ChoiceSummary, temp, by=c("SbjID", "Session_norm", "Week", "ChoiceOption"), all=T)
		ChoiceSummary$LoseShift[is.na(ChoiceSummary$LoseShift)]<-0; ChoiceSummary$LoseStay[is.na(ChoiceSummary$LoseStay)]<-0; ChoiceSummary$TotLosses[is.na(ChoiceSummary$TotLosses)]<-0
	#Calculate general switches by choice option
		temp<-data %>% count(SbjID, Session_norm, Pre.Injury, Week, LastChoice, StaySwitch)
		temp<-subset(temp, !is.na(StaySwitch))
		temp<-temp %>% spread(StaySwitch, n)
		colnames(temp)[colnames(temp)=="2"]<-"Switches"
		colnames(temp)[colnames(temp)=="1"]<-"Stays"
		temp$Switches[is.na(temp$Switches)]<-0
		temp$Stays[is.na(temp$Stays)]<-0
		colnames(temp)[colnames(temp)=="LastChoice"]<-"ChoiceOption"
		ChoiceSummary<-merge(ChoiceSummary, temp, by=c("SbjID", "Session_norm", "Pre.Injury", "Week", "ChoiceOption"), all=T)
		ChoiceSummary$Switches[is.na(ChoiceSummary$Switches)]<-0; ChoiceSummary$Stays[is.na(ChoiceSummary$Stays)]<-0
	#Convert each choice to percent
			ChoiceSummary$PctChoice<-ChoiceSummary$ChoiceCount/ChoiceSummary$TotChoice*100
	#Eliminate any low-observation sessions (e.g., less than 8 total choices)
			ChoiceSummary<-subset(ChoiceSummary, TotChoice>7)
	#Convert character/numeric columns
		summary(ChoiceSummary)
		names<-c(1,3,5:9)
		ChoiceSummary[,names]<-lapply(ChoiceSummary[,names], as.factor)



##Process a Dataset for all non-choice variables analyses. Choice must be separate due to 4 observations/session
	#This will involve calculations for each important variable, then they will all be brought together into a separate dataset
	#Be careful about averages for some data - for example, latencies can get very weird with straight averages. These should be log transformed first
	#Percent calculations need to be based on total possible trials. Since RGT resets premature trials, calculation differs:
		# %Pre = Pre / (Pre + Tot Trial);	%Om = Om / Tot Trial; 	

	#Count function tabulates first option by whatever you list
	#Make sure to include whatever grouping variables are relevant to your dataset
			RGTVars<-data %>% count(SbjID, Session_norm, Week, Injury, Diet, Drug, Pre.Injury, Study_ID) 
			RGTVars<-subset(RGTVars, select=-n)		#master list to merge with
			
	#Trials
		#A good first one since others will use it to calculate some percents
			temp<-aggregate(Trial~SbjID+Session_norm+Pre.Injury, max, data=data)
			colnames(temp)[colnames(temp)=="Trial"] <- "Trials"
			RGTVars<-merge(RGTVars, temp, by=c("SbjID", "Session_norm", "Pre.Injury"))
	#Premature Responses
		#Count up responses in temp, and merge in with main set
			temp<-aggregate(Premature_Resp~SbjID+Session_norm+Pre.Injury, sum, data=data)
			colnames(temp)[colnames(temp)=="Premature_Resp"] <- "Prematures"
			RGTVars<-merge(RGTVars, temp, by=c("SbjID", "Session_norm", "Pre.Injury"), all=T)
	#Omitted Responses
		#Same as Pre's
			temp<-aggregate(Omission~SbjID+Session_norm+Pre.Injury, sum, data=data)
			colnames(temp)[colnames(temp)=="Omission"] <- "Omissions"
			RGTVars<-merge(RGTVars, temp, by=c("SbjID", "Session_norm", "Pre.Injury"), all=T)
	#Pellets Earned
			temp<-aggregate(Pellets~SbjID+Session_norm+Pre.Injury, sum, data=data)
			RGTVars<-merge(RGTVars, temp, by=c("SbjID", "Session_norm", "Pre.Injury"), all=T)
				#Check for NA. It would be really rare, but could happen			
	#Choice Latency
			data$log_Choice_Lat<-log(data$Choice_Lat)
				#Will throw a bunch of infities for 0, but we want to eliminate 0's anyway
			data$log_Choice_Lat[is.infinite(data$log_Choice_Lat)]<-NA
			temp<-aggregate(log_Choice_Lat~SbjID+Session_norm+Pre.Injury, mean, data=data)
			colnames(temp)[colnames(temp)=="log_Choice_Lat"] <- "logChoiceLat"
			RGTVars<-merge(RGTVars, temp, by=c("SbjID", "Session_norm", "Pre.Injury"), all=T)
	#Collection Latency
			data$log_Collect_Lat<-log(data$Collect_Lat)
				#Will throw a bunch of infinites for 0, but we want to eliminate 0's anyway
			data$log_Collect_Lat[is.infinite(data$log_Collect_Lat)]<-NA
			temp<-aggregate(log_Collect_Lat~SbjID+Session_norm+Pre.Injury, mean, data=data)
			colnames(temp)[colnames(temp)=="log_Collect_Lat"] <- "logColLat"
			RGTVars<-merge(RGTVars, temp, by=c("SbjID", "Session_norm", "Pre.Injury"), all=T)
	#Win-Stay
			temp<-aggregate(WinStay~SbjID+Session_norm+Pre.Injury, mean, data=data)
			RGTVars<-merge(RGTVars, temp, by=c("SbjID", "Session_norm", "Pre.Injury"), all=T)
	#Lose-Shift
			temp<-aggregate(LoseShift~SbjID+Session_norm+Pre.Injury, mean, data=data)
			RGTVars<-merge(RGTVars, temp, by=c("SbjID", "Session_norm", "Pre.Injury"), all=T)
	#Choice Score Variable
			#Must be calculated after the choice ones above.
			temp<-aggregate(PctChoice~SbjID+Session_norm+Pre.Injury, sum, data=subset(ChoiceSummary, ChoiceOption=="1"|ChoiceOption=="2"))
			colnames(temp)[colnames(temp)=="PctChoice"] <- "Safe"
			temp<-merge(temp, aggregate(PctChoice~SbjID+Session_norm+Pre.Injury, sum, data=subset(ChoiceSummary, ChoiceOption=="3"|ChoiceOption=="4")))
			colnames(temp)[colnames(temp)=="PctChoice"] <- "Risky"
			temp$Score<-temp$Safe-temp$Risky
			temp<-temp[,c(-4,-5)]
			RGTVars<-merge(RGTVars, temp, by=c("SbjID", "Session_norm", "Pre.Injury"), all=T)
	#Convert various variables to percents. Create new variables if you want to keep counts
			RGTVars$Prematures<-RGTVars$Prematures/(RGTVars$Prematures+RGTVars$Trials)*100
			RGTVars$Omissions<-RGTVars$Omissions/RGTVars$Trials*100
	#Eliminate any low-observation sessions (e.g., less than 10 total trials)
			RGTVars<-subset(RGTVars, Trials>9)
	#Convert character/numeric columns
		summary(RGTVars)
		names<-c(1,3,5:8)
		RGTVars[,names]<-lapply(RGTVars[,names], as.factor)








##Get subset with no interventions and at "stable" time point (10+ ses, post-injury only):
	#Could grab more sham data by pulling pre-injury data - last 5 sessions?


#Maximal sham set - trained pre-injury to get all, and only sham post-injury
	#Sham Choice Set
		temp<-rbind(
			subset(ChoiceSummary, Injury=="Sham" & Session_norm>14 & Pre.Injury=="Pre" & (is.na(Drug) | Drug=="Sal") & (is.na(Diet) | Diet=="LFD")),
			subset(ChoiceSummary, Injury=="Sham" & Session_norm>10 & Pre.Injury=="Post" & (is.na(Drug) | Drug=="Sal") & (is.na(Diet) | Diet=="LFD")))
		ShamChoice<-aggregate(cbind(ChoiceCount, TotChoice, Pun_Dur, Pellets, WinStay, WinShift, LoseStay, LoseShift, TotWins, TotLosses, Stays, Switches)~SbjID+Session_norm+Pre.Injury+Study_ID+ChoiceOption, data=temp, FUN=mean)
		ShamChoice$Injury<-"Sham"
	#Sham All Data Combined
		ShamAllVars<-spread(subset(ShamChoice, select=-(Pun_Dur:Switches)), ChoiceOption, ChoiceCount)
		colnames(ShamAllVars)[7:10]<-c("P1","P2","P3","P4")
		temp<-rbind(
			subset(RGTVars, Injury=="Sham" & Session_norm>14 & Pre.Injury=="Pre"),
			subset(RGTVars, Injury=="Sham" & Session_norm>10 & Pre.Injury=="Post"))
		temp<-subset(temp, select=-c(Week, Diet, Drug, Injury))
		ShamAllVars<-merge(ShamAllVars, temp, by=c("SbjID", "Session_norm", "Pre.Injury", "Study_ID"))
#TBI Set
	#TBI Choice Set
		temp<-subset(ChoiceSummary, Injury=="TBI" & Session_norm>10 & Pre.Injury=="Post" & (is.na(Drug) | Drug=="Sal") & (is.na(Diet) | Diet=="LFD"))
		TBIChoice<-aggregate(cbind(ChoiceCount, TotChoice, Pun_Dur, Pellets, WinStay, WinShift, LoseStay, LoseShift, TotWins, TotLosses, Stays, Switches)~SbjID+Session_norm+Pre.Injury+Study_ID+ChoiceOption, data=temp, FUN=mean)
		TBIChoice$Injury<-"TBI"
	#TBI All Data
		TBIAllVars<-spread(subset(TBIChoice, select=-(Pun_Dur:Switches)), ChoiceOption, ChoiceCount)
		colnames(TBIAllVars)[7:10]<-c("P1","P2","P3","P4")
		temp<-subset(RGTVars, Injury=="TBI" & Session_norm>10 & Pre.Injury=="Post" & (is.na(Drug) | Drug=="Sal") & (is.na(Diet) | Diet=="LFD"))
		temp<-subset(temp, select=-c(Week, Diet, Drug, Injury))
		TBIAllVars<-merge(TBIAllVars, temp, by=c("SbjID", "Session_norm", "Pre.Injury", "Study_ID"))

Choice<-rbind(ShamChoice, TBIChoice)
AllVars<-rbind(ShamAllVars, TBIAllVars)
Choice$Injury<-as.factor(Choice$Injury)
TBIChoice$Injury<-as.factor(TBIChoice$Injury)
ShamChoice$Injury<-as.factor(ShamChoice$Injury)







#Show basic injury differences - Choice over time

temp<-subset(AllVars, Pre.Injury=="Post" & Session_norm>10)
temp<-gather(temp[,-c(11:19)], "Choice", "Pct", P1:P4, factor_key = T)
temp$Pct<-temp$Pct/temp$TotChoice*100

library(lattice)
xyplot(Pct~Session_norm|Choice, group=Injury, data=subset(temp, Session_norm<30), type="a",
       lwd=6, as.table=T,
       ylim=c(-5,105),
       xlim=c(8,32),
       ylab = list(label="% Choice", cex=1.7, fontface="bold"), 
       xlab = list(label="Session Post-Injury", cex=1.7, fontface="bold"),
       par.settings = list(axis.line = list(lwd = 3), 
                           superpose.line = list(lwd=4, col = c("black", "red")),
                           strip.border=list(lwd=3),
                           layout.heights=list(strip=1.55)),
       strip = strip.custom(bg="grey", par.strip.text=list(cex=1.4, fontface="bold"), 
                            factor.levels=c('P1 - Suboptimal','P2 - Optimal','P3 - Risky','P4 - Risky')),
       scales=list(
         cex=c(1.4,1.4), tck=c(1.5,0), fontface="bold", lwd=3, alternating=c(1,1)),
       auto.key=list(
         text=c("Sham","TBI"),
         points=F, lines=T, cex=1.5, fontface="bold",
         corner=c(.97,.38)))

library(lmerTest)
library(MuMIn)
a<-(lmer(scale(asin(sqrt(Pct/100)))~Injury*scale(Session_norm) + (1|SbjID), data=subset(temp, Session_norm<30 & Choice=="P1")))
b<-(lmer(scale(asin(sqrt(Pct/100)))~Injury*scale(Session_norm) + (Session_norm|SbjID), data=subset(temp, Session_norm<30 & Choice=="P1")))
AIC(a,b)
r.squaredGLMM(a); r.squaredGLMM(b)
text<-"P1 - Sbj vs. Sbj+Slope rand effects"
write.table(text, "OverallAnalysis.csv", sep=",", col.names = NA)
write.table(AIC(a,b), "OverallAnalysis.csv", sep=",", col.names = NA, append=T)
write.table(r.squaredGLMM(a), "OverallAnalysis.csv", sep=",", col.names = NA, append=T)
write.table(r.squaredGLMM(b), "OverallAnalysis.csv", sep=",", col.names = NA, append=T)
write.table(summary(b)$varcor, "OverallAnalysis.csv", sep=",", col.names = NA, append=T)
write.table(summary(b)$coef, "OverallAnalysis.csv", sep=",", col.names = NA, append=T)
summary(b)

a<-(lmer(scale(asin(sqrt(Pct/100)))~Injury*scale(Session_norm) + (1|SbjID), data=subset(temp, Session_norm<30 & Choice=="P2")))
b<-(lmer(scale(asin(sqrt(Pct/100)))~Injury*scale(Session_norm) + (Session_norm|SbjID), data=subset(temp, Session_norm<30 & Choice=="P2")))
AIC(a,b)
r.squaredGLMM(a); r.squaredGLMM(b)
text<-"P2 - Sbj vs. Sbj+Slope rand effects"
write.table(text, "OverallAnalysis.csv", sep=",", col.names = NA, append=T)
write.table(AIC(a,b), "OverallAnalysis.csv", sep=",", col.names = NA, append=T)
write.table(r.squaredGLMM(a), "OverallAnalysis.csv", sep=",", col.names = NA, append=T)
write.table(r.squaredGLMM(b), "OverallAnalysis.csv", sep=",", col.names = NA, append=T)
write.table(summary(b)$varcor, "OverallAnalysis.csv", sep=",", col.names = NA, append=T)
write.table(summary(b)$coef, "OverallAnalysis.csv", sep=",", col.names = NA, append=T)

a<-(lmer(scale(asin(sqrt(Pct/100)))~Injury*scale(Session_norm) + (1|SbjID), data=subset(temp, Session_norm<30 & Choice=="P3")))
b<-(lmer(scale(asin(sqrt(Pct/100)))~Injury*scale(Session_norm) + (Session_norm|SbjID), data=subset(temp, Session_norm<30 & Choice=="P3")))
AIC(a,b)
r.squaredGLMM(a); r.squaredGLMM(b)
text<-"P3 - Sbj vs. Sbj+Slope rand effects"
write.table(text, "OverallAnalysis.csv", sep=",", col.names = NA, append=T)
write.table(AIC(a,b), "OverallAnalysis.csv", sep=",", col.names = NA, append=T)
write.table(r.squaredGLMM(a), "OverallAnalysis.csv", sep=",", col.names = NA, append=T)
write.table(r.squaredGLMM(b), "OverallAnalysis.csv", sep=",", col.names = NA, append=T)
write.table(summary(b)$varcor, "OverallAnalysis.csv", sep=",", col.names = NA, append=T)
write.table(summary(b)$coef, "OverallAnalysis.csv", sep=",", col.names = NA, append=T)

a<-(lmer(scale(asin(sqrt(Pct/100)))~Injury*scale(Session_norm) + (1|SbjID), data=subset(temp, Session_norm<30 & Choice=="P4")))
b<-(lmer(scale(asin(sqrt(Pct/100)))~Injury*scale(Session_norm) + (Session_norm|SbjID), data=subset(temp, Session_norm<30 & Choice=="P4")))
AIC(a,b)
r.squaredGLMM(a); r.squaredGLMM(b)
text<-"P4 - Sbj vs. Sbj+Slope rand effects"
write.table(text, "OverallAnalysis.csv", sep=",", col.names = NA, append=T)
write.table(AIC(a,b), "OverallAnalysis.csv", sep=",", col.names = NA, append=T)
write.table(r.squaredGLMM(a), "OverallAnalysis.csv", sep=",", col.names = NA, append=T)
write.table(r.squaredGLMM(b), "OverallAnalysis.csv", sep=",", col.names = NA, append=T)
write.table(summary(b)$varcor, "OverallAnalysis.csv", sep=",", col.names = NA, append=T)
write.table(summary(b)$coef, "OverallAnalysis.csv", sep=",", col.names = NA, append=T)


densityplot(~Pct|Choice, group=Injury, data=temp,
            lwd=6, pch=32, as.table=T,
            #ylim=c(-0.005,0.105),
            xlim=c(-10,115),
            ylab = list(label="Density", cex=1.7, fontface="bold"), 
            xlab = list(label="% Choice", cex=1.7, fontface="bold"),
            par.settings = list(axis.line = list(lwd = 3), 
                                superpose.line = list(lwd=4, col = c("black", "red")),
                                strip.border=list(lwd=3),
                                layout.heights=list(strip=1.55)),
            strip = strip.custom(bg="grey", par.strip.text=list(cex=1.4, fontface="bold"), 
                                 factor.levels=c('P1 - Suboptimal','P2 - Optimal','P3 - Risky','P4 - Risky')),
            scales=list(y=list(relation="free"),
              cex=c(1.4,1.4), tck=c(1.5,0), fontface="bold", lwd=3, alternating=c(1,1)),
            auto.key=list(
              text=c("Sham","TBI"),
              lines=T, cex=1.5, fontface="bold",
              corner=c(.97,.38)))

library(plotrix)
avg<-aggregate(Pct~Choice+Injury+Session_norm, data=temp, FUN=mean)
dev<-aggregate(Pct~Choice+Injury+Session_norm, data=temp, FUN=sd)
er<-aggregate(Pct~Choice+Injury+Session_norm, data=temp, FUN=std.error)
temp<-merge(avg, dev, by=c("Choice", "Injury", "Session_norm"), all=T)
temp<-merge(temp, er, by=c("Choice", "Injury", "Session_norm"), all=T)
colnames(temp)[4:6]<-c("Pct", "SD", "StdErr")
#Save for plotting in SigmaPlot
  write.table(temp, "SummaryDescriptives.csv", sep=",", col.names = NA)


  
  
#Then show correlations/relations between measures for Sham and TBI

avg<-aggregate(.~SbjID+Study_ID+Injury, data=subset(AllVars, Pre.Injury=="Post"), FUN=mean)
  
library("Hmisc")
AllCorMatrix <- rcorr(as.matrix(avg[,c(7:10, 12,13, 15:18)]))
  #removed measures totally dependent on others: Pellets = choice+trials-pre-om, trials=pre+choice+om, score=choice
AllCorMatrix$r
AllCorMatrix$P

temp<-"Correlation between Measures"
write.table(temp, file="Correlations.csv", sep=",", na="")
temp<-"Correlations"
write.table(temp, file="Correlations.csv", sep=",", na="", append=TRUE, col.names=NA)
write.table(AllCorMatrix$r, file="Correlations.csv", sep=",", na="", append=TRUE, col.names=NA)
temp<-"P Values"
write.table(temp, file="Correlations.csv", sep=",", na="", append=TRUE, col.names=NA)
write.table(AllCorMatrix$P, file="Correlations.csv", sep=",", na="", append=TRUE, col.names=NA)



#Make comparison of craniectomy vs. non-craniectomy sham
  #CCI-A - both
    #C: 2, 4, 6, 9, 14, 19, 26, 32, 35, 38, 43, 48
    #I: 5, 7, 8, 15, 16, 23, 30, 36, 37, 42, 46
  #HFD-A - intact
  #CCI-D - intact
  #CCI-E - craniectomy

temp<-subset(AllVars, Pre.Injury=="Post" & Session_norm>10 & Injury=="Sham")
temp<-gather(temp[,-c(11:19)], "Choice", "Pct", P1:P4, factor_key = T)
temp$Pct<-temp$Pct/temp$TotChoice*100
temp$Craniectomy[temp$Study_ID=="HFD-A"]<-"I"
temp$Craniectomy[temp$Study_ID=="CCI-D"]<-"I"
temp$Craniectomy[temp$Study_ID=="CCI-E"]<-"C"

temp$tempID<-sapply(strsplit(as.character(temp$SbjID), "-"), "[", 3)

list<-c(2, 4, 6, 9, 14, 19, 26, 32, 35, 38, 43, 48)
levels<-subset(temp, (Study_ID=="CCI-A_AQ" | Study_ID=="CCI-A_SS") & tempID %in% list)
levels<-droplevels(levels)
temp$Craniectomy[temp$SbjID %in% levels(levels$SbjID)]<-"C"

list<-c(5, 7, 8, 15, 16, 23, 30, 36, 37, 42, 46)
levels<-subset(temp, (Study_ID=="CCI-A_AQ" | Study_ID=="CCI-A_SS") & tempID %in% list)
levels<-droplevels(levels)
temp$Craniectomy[temp$SbjID %in% levels(levels$SbjID)]<-"I"

xyplot(Pct~Session_norm|Choice, group=Craniectomy, data=subset(temp, Session_norm<30), type="a",
       lwd=6, as.table=T,
       ylim=c(-5,105),
       xlim=c(8,32),
       ylab = list(label="% Choice", cex=1.7, fontface="bold"), 
       xlab = list(label="Session Post-Injury", cex=1.7, fontface="bold"),
       par.settings = list(axis.line = list(lwd = 3), 
                           superpose.line = list(lwd=4, col = c("black", "red")),
                           strip.border=list(lwd=3),
                           layout.heights=list(strip=1.55)),
       strip = strip.custom(bg="grey", par.strip.text=list(cex=1.4, fontface="bold"), 
                            factor.levels=c('P1 - Suboptimal','P2 - Optimal','P3 - Risky','P4 - Risky')),
       scales=list(
         cex=c(1.4,1.4), tck=c(1.5,0), fontface="bold", lwd=3, alternating=c(1,1)),
       auto.key=list(
         text=c("Craniectomy","Intact"),
         points=F, lines=T, cex=1.5, fontface="bold",
         corner=c(.97,.38)))

a<-(lmer(scale(asin(sqrt(Pct/100)))~Craniectomy*scale(Session_norm) + (1|SbjID), data=subset(temp, Session_norm<30 & Choice=="P1")))
b<-(lmer(scale(asin(sqrt(Pct/100)))~Craniectomy*scale(Session_norm) + (Session_norm|SbjID), data=subset(temp, Session_norm<30 & Choice=="P1")))
AIC(a,b)
anova(b)

a<-(lmer(scale(asin(sqrt(Pct/100)))~Craniectomy*scale(Session_norm) + (1|SbjID), data=subset(temp, Session_norm<30 & Choice=="P2")))
b<-(lmer(scale(asin(sqrt(Pct/100)))~Craniectomy*scale(Session_norm) + (Session_norm|SbjID), data=subset(temp, Session_norm<30 & Choice=="P2")))
AIC(a,b)
anova(b)

a<-(lmer(scale(asin(sqrt(Pct/100)))~Craniectomy*scale(Session_norm) + (1|SbjID), data=subset(temp, Session_norm<30 & Choice=="P3")))
b<-(lmer(scale(asin(sqrt(Pct/100)))~Craniectomy*scale(Session_norm) + (Session_norm|SbjID), data=subset(temp, Session_norm<30 & Choice=="P3")))
AIC(a,b)
anova(b)

a<-(lmer(scale(asin(sqrt(Pct/100)))~Craniectomy*scale(Session_norm) + (1|SbjID), data=subset(temp, Session_norm<30 & Choice=="P4")))
b<-(lmer(scale(asin(sqrt(Pct/100)))~Craniectomy*scale(Session_norm) + (Session_norm|SbjID), data=subset(temp, Session_norm<30 & Choice=="P4")))
AIC(a,b)
anova(b)


avg<-aggregate(Pct~Choice+Craniectomy+Session_norm, data=temp, FUN=mean)
dev<-aggregate(Pct~Choice+Craniectomy+Session_norm, data=temp, FUN=sd)
er<-aggregate(Pct~Choice+Craniectomy+Session_norm, data=temp, FUN=std.error)
temp<-merge(avg, dev, by=c("Choice", "Craniectomy", "Session_norm"), all=T)
temp<-merge(temp, er, by=c("Choice", "Craniectomy", "Session_norm"), all=T)
colnames(temp)[4:6]<-c("Pct", "SD", "StdErr")
#Save for plotting in SigmaPlot
write.table(temp, "SummaryDescriptives.csv", sep=",", col.names = NA, append=T)
